import type { Metadata } from 'next'
import { Inter, Noto_Sans } from 'next/font/google'
import './globals.scss'
import classNames from 'classnames';

const inter = Inter({ 
  subsets: ['latin'] 
});

const noto = Noto_Sans({
  weight: ['400', '700'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
})


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={classNames(inter.className, noto.className)}>{children}</body>
    </html>
  )
}
