import type { Metadata } from 'next'
import { Inter, Noto_Sans } from 'next/font/google'
import './globals.scss'
import classNames from 'classnames';

const inter = Inter({ 
  weight: ['200', '300','400', '500', '600', '700'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-latin',
});

const noto = Noto_Sans({
  weight: ['200', '300','400', '500', '600', '700'],
  style: ['normal', 'italic'],
  subsets: ['latin', "cyrillic"],
  
  variable: '--font-noto',
})


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={classNames(noto.className, inter.className)}>{children}</body>
    </html>
  )
}
